<!--
Configuration options for xExtension-RssBridge
Copyright (C) 2025  David Marmor

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="rss_bridge_url"><?php echo _t('ext.rssbridge.url'); ?></label>
		<div class="group-controls">
			<input type="url" name="rss_bridge_url" id="rss_bridge_url" value="<?php echo FreshRSS_Context::$system_conf->rss_bridge_url; ?>">
		</div>
	</div>

	<div class="form-group">
		<label class="group-name" for="rss_bridge_token"><?php echo _t('ext.rssbridge.token'); ?></label>
		<div class="group-controls">
			<input type="text" name="rss_bridge_token" id="rss_bridge_token" value="<?php echo FreshRSS_Context::$system_conf->rss_bridge_token; ?>" placeholder="Optional authentication token">
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>
