
<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
        
    
    <div class="form-group">
    
        <div class="group-name"><strong><?php echo _t('ext.videoembed.site_selection'); ?></strong></div>
        <div class="group-controls"></div>

        <div class="group-controls">
            <label class="checkbox" for="tiktok_enabled">
                <input type="checkbox" name="tiktok_enabled" id="tiktok_enabled" value="1" <?php echo (FreshRSS_Context::$user_conf->videoembed_tiktok_enabled ?? true) ? 'checked' : ''; ?> />
                <?php echo _t('ext.videoembed.tiktok_short'); ?>
            </label>
        </div>
    
        <div class="group-controls">
            <label class="checkbox" for="youtube_enabled">
                <input type="checkbox" name="youtube_enabled" id="youtube_enabled" value="1" <?php echo (FreshRSS_Context::$user_conf->videoembed_youtube_enabled ?? true) ? 'checked' : ''; ?> />
                <?php echo _t('ext.videoembed.youtube_short'); ?>
            </label>
            <label class="checkbox" for="youtube_show_description">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="checkbox" name="youtube_show_description" id="youtube_show_description" value="1" <?php echo (FreshRSS_Context::$user_conf->videoembed_youtube_show_description ?? false) ? 'checked' : ''; ?> />
                <?php echo _t('ext.videoembed.youtube_description_short'); ?>
            </label>
        </div>
    </div>

    <div class="form-group form-actions">
        <div class="group-controls">
            <button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
            <button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
        </div>
    </div>
</form>